**Creation of ndarray**

1. Write python code to create 3d array in different ways with 15 elements.
2. Array Creation:
a. Create a 4D NumPy array containing the first 12 positive integers as arr1.
b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1.
3. Find all attributes of array1 and array2
4. Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.


**Array Slicing and Indexing:**

a. Creating Arrays:
      - Create a 1-dimensional NumPy array  arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29].
      - Create a 2-dimensional NumPy array  arr2  with the values  [[0, 1, 2], [3, 4, 5], [6, 7, 8]].
      
 b.Basic Indexing:
      - Print the element at index 3 of  arr1.
      - Print the element at row 2, column 1 of  arr2

   c. Array Slicing:
      - Print the first five elements of `arr1`.
      - Print the subarray of `arr2` consisting of the last two rows and the first two columns.
       - Print every second element starting from index 1 up to index 7 of `arr1`.







**Data Type Manipulation**

a. Creating Arrays with Specific Data Types:
      - Create a 1-dimensional NumPy array `int_array` with the values `[1, 2, 3, 4, 5]` and the data type `int16`.
      - Create a 1-dimensional NumPy array `float_array` with the values `[0.1, 0.2, 0.3, 0.4, 0.5]` and the data type `float64`.
      
b. Data Type Conversion:
      - Convert the `float_array` to an array with data type `int32`. Print the result.
      - Convert the `int_array` to an array with data type `float32`. Print the result.

**Generating Random Numbers:**

1.	Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).

2.	Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.

3.	Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix

4.	Apply descriptive statistics for rand_matrix.


**Analyze the Data:**

Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]




Describe the data using numpy array.
Measure the following:
1.	How many employees are getting more less than 50000?

2.	Is it following Normal Distribution?

3.	What is the median salary?

4.	What is the range of salaries for this company?

5.	Find the salaries between average salary and 75% of salaries?

6.	How many employees are getting less than 25 % of salaries ?



In [1]:
import numpy as np

In [2]:
array1 = np.array([[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]]])
array1

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [3]:
array1 = np.array([[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]]],ndmin=3)
array1

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [4]:
array1.reshape(1,3,5)
array1

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [5]:
array1 = np.arange(1,16).reshape(1,3,5)
array1

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [6]:
arr1 = np.arange(1,13).reshape(1,1,4,3)
arr1

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [7]:
array2 = np.random.rand(20).reshape(1,4,5)
array2

array([[[0.39371003, 0.01491549, 0.19451202, 0.78122713, 0.89459533],
        [0.17367829, 0.08819248, 0.80840284, 0.23762814, 0.55871958],
        [0.72183503, 0.68645996, 0.88713259, 0.03063247, 0.31754411],
        [0.83794203, 0.55679201, 0.60458384, 0.41910374, 0.28927337]]])

### Attributes of arr1

In [8]:
arr1

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [9]:
arr1.dtype

dtype('int32')

In [10]:
arr1.ndim

4

In [11]:
arr1.size

12

In [12]:
arr1.itemsize

4

In [13]:
arr1.nbytes

48

### Attributes of array2

In [14]:
array2

array([[[0.39371003, 0.01491549, 0.19451202, 0.78122713, 0.89459533],
        [0.17367829, 0.08819248, 0.80840284, 0.23762814, 0.55871958],
        [0.72183503, 0.68645996, 0.88713259, 0.03063247, 0.31754411],
        [0.83794203, 0.55679201, 0.60458384, 0.41910374, 0.28927337]]])

In [15]:
array2.dtype

dtype('float64')

In [16]:
array2.ndim

3

In [17]:
array2.itemsize

8

In [18]:
array2.nbytes

160

In [19]:
array2.size

20

### Applying Descriptive statistics on arr1

In [20]:
arr1

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [21]:
arr1.mean()

6.5

In [22]:
np.median(arr1)

6.5

In [23]:
arr1.var()

11.916666666666666

In [24]:
arr1.std()

3.452052529534663

In [25]:
range = arr1.max()-arr1.min()
range

11

In [26]:
q1 = np.percentile(arr1,25)
q1

3.75

In [27]:
q3 = np.percentile(arr1,75)
q3

9.25

In [28]:
IQR = q3 - q1
IQR

5.5

In [29]:
lower_limit = q1 - (1.5 * IQR)
lower_limit

-4.5

In [30]:
upper_limit = q3  +  (1.5 * IQR)
upper_limit

17.5

In [31]:
arr1[arr1<lower_limit]

array([], dtype=int32)

In [32]:
arr1[arr1>upper_limit]

array([], dtype=int32)

### Applying Descriptive statistics on array2

In [33]:
array2

array([[[0.39371003, 0.01491549, 0.19451202, 0.78122713, 0.89459533],
        [0.17367829, 0.08819248, 0.80840284, 0.23762814, 0.55871958],
        [0.72183503, 0.68645996, 0.88713259, 0.03063247, 0.31754411],
        [0.83794203, 0.55679201, 0.60458384, 0.41910374, 0.28927337]]])

In [34]:
array2.mean()

0.474844024751346

In [35]:
np.median(array2)

0.48794787679117235

In [36]:
range = array2.max()-array2.min()
range

0.8796798477462493

In [37]:
array2.var()

0.08361496797827235

In [38]:
array2.std()

0.28916252865520514

In [39]:
q1 = np.percentile(array2,25)
q1

0.22684911454559217

In [40]:
q3 = np.percentile(array2,75)
q3

0.736683052253369

In [41]:
IQR = q3-q1
IQR

0.5098339377077769

In [42]:
lower_limit = q1 - (1.5*IQR)
lower_limit

-0.5379017920160731

In [43]:
upper_limit = q3 + (1.5*IQR)
upper_limit

1.5014339588150345

In [44]:
array2[array2<lower_limit]

array([], dtype=float64)

In [45]:
array2[array2>upper_limit]

array([], dtype=float64)

## Array Slicing and Indexing:
a. Creating Arrays: - Create a 1-dimensional NumPy array arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29]. - Create a 2-dimensional NumPy array arr2 with the values [[0, 1, 2], [3, 4, 5], [6, 7, 8]].

b.Basic Indexing: - Print the element at index 3 of arr1. - Print the element at row 2, column 1 of arr2

c. Array Slicing: - Print the first five elements of arr1. - Print the subarray of arr2 consisting of the last two rows and the first two columns. - Print every second element starting from index 1 up to index 7 of arr1.

In [46]:
n1 = np.array([0, 11, 26, 73, 42, 51, 6,77, 8,29])
n1

array([ 0, 11, 26, 73, 42, 51,  6, 77,  8, 29])

In [47]:
n2 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
n2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
n1[3]

73

In [52]:
n2[2][1]

7

In [53]:
n1[:5]

array([ 0, 11, 26, 73, 42])

In [54]:
n2[1:,0:2]

array([[3, 4],
       [6, 7]])

In [55]:
n1[1:8]

array([11, 26, 73, 42, 51,  6, 77])

## Data Type Manipulation
a. Creating Arrays with Specific Data Types: - Create a 1-dimensional NumPy array int_array with the values [1, 2, 3, 4, 5] and the data type int16. - Create a 1-dimensional NumPy array float_array with the values [0.1, 0.2, 0.3, 0.4, 0.5] and the data type float64.

b. Data Type Conversion: - Convert the float_array to an array with data type int32. Print the result. - Convert the int_array to an array with data type float32. Print the result.

In [56]:
a = np.array([1, 2, 3, 4, 5],dtype = "int16")

In [57]:
a.dtype

dtype('int16')

In [58]:
a.dtype

dtype('int16')

In [59]:
b = np.array([0.1, 0.2, 0.3, 0.4, 0.5],dtype = "int32")
b.dtype

dtype('int32')

In [60]:
c = np.array([1, 2, 3, 4, 5],dtype = "float32")
c

array([1., 2., 3., 4., 5.], dtype=float32)

## Generating Random Numbers:
Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).

Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.

Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix

Apply descriptive statistics for rand_matrix.

In [61]:
n = np.random.randint(0,101,10)
n

array([ 44,  97,  36,  60,  23,  36,  10,   7,  16, 100])

In [62]:
np.random.uniform(-1,1,5)

array([ 0.80004684,  0.34477362,  0.05331392, -0.12830511, -0.84030973])

In [63]:
rand_matrix = np.random.randint(50,101,16).reshape(4,4)
rand_matrix

array([[51, 64, 91, 89],
       [52, 74, 85, 55],
       [87, 90, 59, 91],
       [71, 74, 98, 80]])

### Descriptive statistics for rand_matrix.

In [64]:
rand_matrix.mean()

75.6875

In [65]:
np.median(rand_matrix)

77.0

In [66]:
rand_matrix.max()-rand_matrix.min()
rand_matrix

array([[51, 64, 91, 89],
       [52, 74, 85, 55],
       [87, 90, 59, 91],
       [71, 74, 98, 80]])

In [67]:
rand_matrix.std()

15.048748909793133

In [68]:
rand_matrix.var()

226.46484375

In [69]:
q1 = np.percentile(rand_matrix,25)
q1

62.75

In [70]:
q3 = np.percentile(rand_matrix,75)
q3

89.25

In [71]:
IQR = q3-q1
IQR

26.5

In [72]:
lower = q1 - (1.5 * IQR)
lower

23.0

In [73]:
upper = q3 + (1.5 * IQR)
upper

129.0

In [74]:
rand_matrix[rand_matrix < lower]

array([], dtype=int32)

In [75]:
rand_matrix[rand_matrix > upper]

array([], dtype=int32)

## Analyze the Data:
Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]

Describe the data using numpy array. Measure the following: 1. How many employees are getting more less than 50000?

Is it following Normal Distribution?

What is the median salary?

What is the range of salaries for this company?

Find the salaries between average salary and 75% of salaries?

How many employees are getting less than 25 % of salaries ?

In [77]:
salaries = np.array([87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638])


In [78]:
salaries[salaries < 50000]

array([31250, 39828, 41671, 34225, 32199])

In [79]:
np.median(salaries)  # median salary

61699.5

In [80]:
salaries.max() - salaries.min() # range

3082388

In [81]:
avg = salaries.mean()
avg

166169.16666666666

In [82]:
q1 = np.percentile(salaries,25)
q1

52963.25

In [83]:
q3 = np.percentile(salaries,75)
q3

84496.5

In [84]:
salaries[(salaries > avg) & (salaries <= q3)]

array([], dtype=int32)

In [85]:
IQR = q3-q1
IQR                 # finding outliers

31533.25

In [86]:
lower = q1 - (1.5 * IQR)
lower

5663.375

In [87]:
upper = q3 + (1.5 * IQR)
upper

131796.375

In [88]:
salaries[salaries<lower]

array([], dtype=int32)

In [89]:
salaries[salaries>upper]

array([3113638])