In [1]:
import numpy as np

# **Creating an Array**

In [2]:
num = np.array([2,4,6,8,10,12,14,16,20])
num

array([ 2,  4,  6,  8, 10, 12, 14, 16, 20])

In [3]:
num1 =[1,2,12,15,17,22]

In [4]:
n = np.array(num1)
n

array([ 1,  2, 12, 15, 17, 22])

In [5]:
tuple1 = (1,15,22,24,16,19,27)

In [6]:
np.array(tuple1)

array([ 1, 15, 22, 24, 16, 19, 27])

In [7]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.arange(1,29)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [10]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

### 2. Create a 1D NumPy array containing the first 12 positive integer as arr1 

In [11]:
arr1 = np.array(range(1,13))

In [12]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Create an array containing 20 elements from 0 to 12 using linspace

In [13]:
arr2 = np.linspace(0,12,20)
arr2

array([ 0.        ,  0.63157895,  1.26315789,  1.89473684,  2.52631579,
        3.15789474,  3.78947368,  4.42105263,  5.05263158,  5.68421053,
        6.31578947,  6.94736842,  7.57894737,  8.21052632,  8.84210526,
        9.47368421, 10.10526316, 10.73684211, 11.36842105, 12.        ])

### Find all the attributes of array1 and array2

In [14]:
arr1.dtype

dtype('int32')

In [15]:
arr1.nbytes

48

In [16]:
arr1.ndim

1

In [18]:
arr1.min()

1

In [19]:
arr1.max()

12

In [20]:
arr2.dtype

dtype('float64')

In [21]:
arr2.nbytes

160

In [22]:
arr2.ndim

1

In [23]:
arr2.max()

12.0

In [24]:
arr2.min()

0.0

### Apply measure and describe the data (attributes and descriptive statistics) to above arrays

In [25]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### measure of tendency of arr1

In [26]:
np.mean(arr1)

6.5

In [27]:
np.median(arr1)

6.5

### measure of spread of arr1

In [28]:
# range
np.max(arr1)

12

In [29]:
np.min(arr1)

1

In [30]:
range = np.max(arr1) - np.min(arr1)
range

11

In [31]:
# variance
np.var(arr1)

11.916666666666666

In [32]:
# standard deviation
np.std(arr1)

3.452052529534663

### IQR for arr1

In [33]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [34]:
q1 = np.percentile(arr1,25)
q1

3.75

In [35]:
q2 = np.percentile(arr1,50)
q2

6.5

In [36]:
q3 = np.percentile(arr1,75)
q3

9.25

In [37]:
IQR = q3 - q1
IQR

5.5

In [38]:
lower_limit = q1 - (1.5 * IQR)
lower_limit

-4.5

In [39]:
upper_limit = q3 + (1.5 * IQR)
upper_limit

17.5

### measure of central tendency of array2

In [41]:
np.mean(arr2)

5.999999999999999

In [42]:
np.median(arr2)

6.0

### measure of spread for array2

In [44]:
# range
np.max(arr2)

12.0

In [45]:
np.min(arr2)

0.0

In [46]:
range = np.max(arr2) - np.min(arr2)
range

12.0

In [47]:
### variance
np.var(arr2)

13.26315789473684

In [48]:
### standard deviation
np.std(arr2)

3.6418618720013036

### IQR for array2

In [50]:
q1 = np.percentile(arr2,25)
q1

3.0

In [52]:
q2 = np.percentile(arr2,50)
q2

6.0

In [53]:
q3 = np.percentile(arr2,75)
q3

9.0

In [54]:
IQR = q3 - q1
IQR

6.0

In [55]:
lower_limit = q1 - (1.5 * IQR)
lower_limit

-6.0

In [56]:
upper_limit = q3 + (1.5 * IQR)
upper_limit

18.0